// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/get": {
            "post": {
                "description": "支持通配符",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET"
                ],
                "summary": "获取远程文件",
                "parameters": [
                    {
                        "description": "远端ep和文件路径",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.GetResponse"
                        }
                    }
                }
            }
        },
        "/list": {
            "post": {
                "description": "支持通配符",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET"
                ],
                "summary": "获取远程文件列表",
                "parameters": [
                    {
                        "description": "远端ep和文件路径",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.ListResponse"
                        }
                    }
                }
            }
        },
        "/put": {
            "post": {
                "description": "支持通配符",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GET"
                ],
                "summary": "put文件到远程",
                "parameters": [
                    {
                        "description": "dst和src file",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/endpoint.PutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoint.PutResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "endpoint.GetRequest": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "localPath": {
                    "type": "string"
                },
                "passwd": {
                    "type": "string"
                },
                "remoteFilePath": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "endpoint.GetResponse": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                },
                "v": {
                    "type": "string"
                }
            }
        },
        "endpoint.ListRequest": {
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string"
                },
                "passwd": {
                    "type": "string"
                },
                "remoteFilePath": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "endpoint.ListResponse": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                },
                "v": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "endpoint.PutRequest": {
            "type": "object",
            "properties": {
                "dstFilePath": {
                    "description": "dst为client所在机器路径",
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "passwd": {
                    "type": "string"
                },
                "srcFilePath": {
                    "description": "src为fileTransfer服务本地文件路径",
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "endpoint.PutResponse": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                },
                "v": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.4.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "运行室 文件传输服务",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
