definitions:
  endpoint.DownloadRequest:
    properties:
      clientDir:
        type: string
      clientIp:
        type: string
      clientPasswd:
        type: string
      clientUser:
        type: string
      remoteFilePath:
        type: string
      remoteIp:
        type: string
      remotePasswd:
        type: string
      remoteUser:
        type: string
    type: object
  endpoint.DownloadResponse:
    properties:
      err:
        type: string
      v:
        type: string
    type: object
  endpoint.GetRequest:
    properties:
      remoteFilePath:
        description: must abs path
        type: string
      remoteIp:
        type: string
      remotePasswd:
        type: string
      remoteUser:
        type: string
      srcDir:
        type: string
    type: object
  endpoint.GetResponse:
    properties:
      err:
        type: string
      v:
        type: string
    type: object
  endpoint.ListRequest:
    properties:
      remoteFilePath:
        type: string
      remoteIp:
        type: string
      remotePasswd:
        type: string
      remoteUser:
        type: string
    type: object
  endpoint.ListResponse:
    properties:
      err:
        type: string
      v:
        items:
          type: string
        type: array
    type: object
  endpoint.PutRequest:
    properties:
      clientDir:
        description: must abs path
        type: string
      clientPasswd:
        type: string
      clientUser:
        type: string
      srcFilePath:
        type: string
    type: object
  endpoint.PutResponse:
    properties:
      err:
        type: string
      v:
        type: string
    type: object
info:
  contact: {}
  license:
    name: Apache 2.0
  title: 文件传输服务
  version: 0.5.0
paths:
  /download:
    post:
      consumes:
      - application/json
      description: 支持通配符
      parameters:
      - description: remote -> client
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/endpoint.DownloadRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.DownloadResponse'
      summary: 从remote端下载文件到client端
      tags:
      - GET
  /get:
    post:
      consumes:
      - application/json
      description: 支持通配符
      parameters:
      - description: remote -> server
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/endpoint.GetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.GetResponse'
      summary: 从remote端拉取文件到server端
      tags:
      - GET
  /list:
    post:
      consumes:
      - application/json
      description: 支持通配符
      parameters:
      - description: remote
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/endpoint.ListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.ListResponse'
      summary: 从remote端获取文件列表
      tags:
      - GET
  /put:
    post:
      consumes:
      - application/json
      description: 支持通配符
      parameters:
      - description: server -> client
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/endpoint.PutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.PutResponse'
      summary: 从server端put文件到client端
      tags:
      - Put
swagger: "2.0"
