definitions:
  endpoint.GetRequest:
    properties:
      ip:
        type: string
      localPath:
        type: string
      passwd:
        type: string
      remoteFilePath:
        type: string
      user:
        type: string
    type: object
  endpoint.GetResponse:
    properties:
      err:
        type: string
      v:
        type: string
    type: object
  endpoint.ListRequest:
    properties:
      ip:
        type: string
      passwd:
        type: string
      remoteFilePath:
        type: string
      user:
        type: string
    type: object
  endpoint.ListResponse:
    properties:
      err:
        type: string
      v:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
  license:
    name: Apache 2.0
  title: 运行室 文件传输服务
  version: 0.2.0
paths:
  /get:
    post:
      consumes:
      - application/json
      description: 支持通配符
      parameters:
      - description: 远端ep和文件路径
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/endpoint.GetRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.GetResponse'
      summary: 获取远程文件
      tags:
      - GET
  /list:
    post:
      consumes:
      - application/json
      description: 支持通配符
      parameters:
      - description: 远端ep和文件路径
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/endpoint.ListRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/endpoint.ListResponse'
      summary: 获取远程文件列表
      tags:
      - GET
swagger: "2.0"
